# app.py
import streamlit as st
import numpy as np
import joblib
import re
import nltk
from nltk.tokenize import word_tokenize
from transformers import pipeline
import torch

import sys
import os

# Allow Streamlit to find modules inside the src/ folder
sys.path.append(os.path.abspath("src"))

# Now import your language model class so joblib can unpickle it correctly
from language_model import BigramLanguageModel # type: ignore

# Ensure NLTK tokenizers are downloaded
# nltk.download('punkt', quiet=True)
# nltk.download('punkt_tab', quiet=True)

# --- Configuration & Cache Loading ---
st.set_page_config(page_title="AI Text Detector Analytics", layout="wide")

# --- Update inside app.py ---

@st.cache_resource
def load_detection_assets():
    """Loads ML artifacts and pipeline cleanly without calling Streamlit UI elements."""
    scaler = None
    naive_bayes_model = None
    language_model = None
    
    try:
        scaler = joblib.load('models/scaler.pkl')
        naive_bayes_model = joblib.load('models/naive_bayes.pkl')
        language_model = joblib.load('models/bigram_language_model.pkl')
        custom_loaded = True
    except Exception:
        custom_loaded = False

    roberta_detector = pipeline(
        "text-classification", 
        model="Hello-SimpleAI/chatgpt-detector-roberta",
        top_k=None,
        device=-1
    )
    
    return scaler, naive_bayes_model, language_model, roberta_detector, custom_loaded

# --- Main Application Logic ---
feature_scaler, nb_model, custom_lm, transformer_model, is_custom_loaded = load_detection_assets()

# Handle UI feedback safely outside the cached function
if not is_custom_loaded:
    st.warning("⚠️ Custom models not loaded — using heuristic fallback.")


# --- Custom Engineering Calculation Functions ---
def calculate_burstiness(text):
    sentences = nltk.sent_tokenize(str(text))
    if len(sentences) <= 1:
        return 0.0
    lengths = [len(word_tokenize(s)) for s in sentences]
    return float(np.std(lengths))

def calculate_perplexity(text, lm_model):
    if not lm_model:
        return 35.42  # Clean default baseline value
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = word_tokenize(text)
    if not tokens:
        return float('inf')
    
    padded = ['<s>'] + tokens + ['</s>']
    log_prob_sum = 0.0
    N = len(padded) - 1
    
    for i in range(N):
        w1, w2 = padded[i], padded[i+1]
        count_w1_w2 = lm_model.bigram_counts[w1][w2]
        count_w1 = lm_model.unigram_counts[w1]
        prob = (count_w1_w2 + 1) / (count_w1 + lm_model.vocab_size)
        log_prob_sum += np.log(prob)
        
    return float(np.exp(-(log_prob_sum / N)))

# --- Dashboard UI Architecture ---
st.title("🔬 AI Text Detection Dashboard")
st.markdown("Check if a text was written by a human or generated by AI using our custom metrics and a baseline deep learning model.")

text_input = st.text_area(
    "Paste the text you want to analyze here:", 
    height=280, 
    placeholder="Type or copy your text here (Minimum 2-3 sentences recommended)..."
)

if st.button("Analyze Text", type="primary"):
    if text_input.strip() == "":
        st.warning("The input area is empty. Please enter some text.")
    else:
        with st.spinner("Analyzing text..."):
            # 1. Structural Engineering calculation metrics 
            pp_score = calculate_perplexity(text_input, custom_lm)
            burst_score = calculate_burstiness(text_input)
            
            # 2. Classifiers Inference processing routines
            if nb_model and feature_scaler:
                features = np.array([[pp_score, burst_score]])
                features_scaled = feature_scaler.transform(features)
                nb_pred = nb_model.predict(features_scaled)[0]
                nb_prob = nb_model.predict_proba(features_scaled)[0][1]
            else:
                st.caption("⚠️ Custom models not loaded — using heuristic fallback.")
                nb_pred = 1 if pp_score > 150 and burst_score < 4.0 else 0
                nb_prob = 0.84 if nb_pred == 1 else 0.12

           # Transformer Pipeline Inference execution
            truncated_inp = " ".join(text_input.split()[:400])
            tf_raw_outputs = transformer_model(truncated_inp)[0]
            
            # Extract distinct AI and Human probabilities safely
            ai_prob = 0.0
            human_prob = 0.0

            for entry in tf_raw_outputs:
                lbl = str(entry['label']).upper()
                score = entry['score']
                if any(tag in lbl for tag in ['CHATGPT', 'LABEL_1', 'FAKE', 'AI']):
                    ai_prob = score
                else:
                    human_prob = score

            # Final verdict determination
            is_ai_generated = ai_prob > human_prob
            
            # --- Results Presentation ---
            st.subheader("Analysis Results")
            col1, col2, col3 = st.columns(3)
            
            with col1:
                st.metric(label="Text Predictability (Perplexity)", value=f"{pp_score:.2f}")
                st.caption("Lower scores mean the text is highly predictable (common for AI).")
                
            with col2:
                st.metric(label="Sentence Variation (Burstiness)", value=f"{burst_score:.2f}")
                st.caption("Lower scores mean sentence lengths are very repetitive (common for AI).")
                
            with col3:
                tf_verdict = f"{'AI Generated' if is_ai_generated else 'Human Written'}"
                # Always displays the exact AI Probability Score
                st.metric(
                    label="AI Probability (RoBERTa Model)", 
                    value=f"{ai_prob*100:.1f}%", 
                    delta=tf_verdict,
                    delta_color="off"
                )
            
            st.divider()
            
            # Comparative Engine Analytics View Block
            st.subheader("Model Predictions")
            m1, m2 = st.columns(2)
            
            with m1:
                st.markdown("### Custom Model (Naive Bayes)")
                if nb_pred == 1:
                    st.warning(f"Verdict: **Likely AI Generated** ({nb_prob*100:.1f}% confidence)")
                else:
                    st.info(f"Verdict: **Likely Human Written** ({(1-nb_prob)*100:.1f}% confidence)")
                    
            with m2:
                st.markdown("### Baseline Model (RoBERTa)")
                if is_ai_generated:
                    st.warning(f"Verdict: **Likely AI Generated** ({ai_prob*100:.1f}% confidence)")
                else:
                    st.info(f"Verdict: **Likely Human Written** ({human_prob*100:.1f}% confidence)")

            st.divider()
            
            # --- Final Layman Summary ---
            st.subheader("The Bottom Line")
            
            if nb_pred == 1 and is_ai_generated:
                st.error("🚨 **Final Verdict:** Both of our detectors agree. This text is highly predictable and lacks natural variation, meaning it was almost certainly generated by an AI.")
                
            elif nb_pred == 0 and not is_ai_generated:
                st.success("✅ **Final Verdict:** Both detectors agree. This text has natural sentence variety and vocabulary, meaning it was almost certainly written by a human.")
                
            elif nb_pred == 1 and not is_ai_generated:
                st.warning("⚖️ **Mixed Results:** The models disagree! The text has a very rigid, robotic structure (flagged by our Custom Model), but the deep learning model thinks it is human. This often happens with highly technical text, bulleted lists, or human notes that were copy-pasted poorly.")
                
            elif nb_pred == 0 and is_ai_generated:
                st.warning("⚖️ **Mixed Results:** The models disagree! The sentence lengths vary nicely like a human wrote it, but the deep learning model thinks the word choices are synthetic. This could be a human writer using very predictable phrasing, or an AI that was specifically prompted to write creatively.")
            